# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/vivadowork/CO-lab-material-CQU/test/func_test_v0.01_n4ddr/soc_sram_func/rtl/xilinx_ip/data_ram/data_ram.xci
# IP: The module: 'data_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/vivadowork/CO-lab-material-CQU/test/func_test_v0.01_n4ddr/soc_sram_func/rtl/xilinx_ip/data_ram/data_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'data_ram'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/vivadowork/CO-lab-material-CQU/test/func_test_v0.01_n4ddr/soc_sram_func/rtl/xilinx_ip/data_ram/data_ram.xci
# IP: The module: 'data_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/vivadowork/CO-lab-material-CQU/test/func_test_v0.01_n4ddr/soc_sram_func/rtl/xilinx_ip/data_ram/data_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'data_ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
